# Generated by Django 5.2.7 on 2025-11-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Write your message here. It will be displayed on the homepage for everyone to see.', verbose_name='Message Content'),
        ),
    ]
