# Generated by Django 5.2.8 on 2025-11-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter student's full name", max_length=100)),
                ('email', models.EmailField(help_text="Enter student's email address", max_length=254, unique=True)),
                ('age', models.IntegerField(help_text="Enter student's age")),
                ('course', models.CharField(help_text='Enter course name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
    ]
